version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    ports:
      - "8080:8080"
    networks:
      - backend
  chat_service:
    build:
      context: ./chat_service
    ports:
      - "8081:8080"
    networks:
      - backend
  friendship_service:
    build:
      context: ./friendship_service
    ports:
      - "8082:8080"
    networks:
      - backend
  media_service:
    build:
      context: ./media_service
    ports:
      - "8083:8080"
    networks:
      - backend
  notification_service:
    build:
      context: ./notification_service
    ports:
      - "8084:8080"
    networks:
      - backend
  search_service:
    build:
      context: ./search_service
    ports:
      - "8085:8080"
    networks:
      - backend
  server_service:
    build:
      context: ./server_service
    ports:
      - "8086:8080"
    networks:
      - backend
  user_profile_service:
    build:
      context: ./user_profile_service
    ports:
      - "8087:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
